### ISSUE TITLE
Only import parts of threejs (module import)

### ISSUE THREAD

**Issue by huygn** [pschroen/alien.js#3]
Currently we are relying on `global THREE` (in `Shader` class for example), I'm not a bundle expert but I assume this will load the whole `three` library right? Since three is already super heavy ~ [130KB](https://bundlephobia.com/result?p=three@0.89.0) minified + gzipped. Therefore can we use module import to bundle only what is needed within `alien.js` internal to reduce bundle size?

ie.

```js
import { Scene } from 'three';

const scene = new Scene();
...
```

**Comment by pschroen** [comment]
`global THREE` is an ESLint global so it doesn't complain about the external functions being used in the class, `THREE.RawShaderMaterial` and `THREE.ShaderChunk`.

The shader examples all currently load the entire three.js library from `dist/assets/js/lib/three.min.js` at runtime.

The classes in `alien.js/src/three/` are meant specifically for three.js, though for a future update open to exploring the same functionality natively without it.

Instead of loading the entire library at runtime you could import three.js as a module (like in your example). This works in your own code but the alien.js `three` classes would need to be updated to work that way as well.

For example:

```sh
npm install --save-dev rollup-plugin-node-resolve
npm install --save-dev three
```

```js
// rollup.config.js
import { timestamp, singletons, babel, uglify } from './alien.js/src/utils.js';

import resolve from 'rollup-plugin-node-resolve';
// ...

export default {
    // ...
    plugins: [
        resolve(),
        // ...
    ]
};
```

```js
// src/Main.js
import * as THREE from 'three';
```

I'll add that to the Roadmap.

Cheers! 😄

**Comment by pschroen** [comment]
The framework has been updated to support both use cases by removing or including `three`. See rollup/rollup#2357 for reference.

By default `three` is removed from the updated `rollup.config.js` using `rollup-plugin-replace`, and you can include it in your project by removing the `replace()` section.

```
npm install --save-dev rollup-plugin-node-resolve
npm install --save-dev three
```

```js
// rollup.config.js
import { timestamp, regex, babel, uglify } from 'rollup-plugin-bundleutils';

import resolve from 'rollup-plugin-node-resolve';
import replace from 'rollup-plugin-replace';
// ...

export default {
    // ...
    plugins: [
        resolve(),
        replace({
            'three': '/* global THREE */',
            delimiters: ['import * as THREE from \'', '\';']
        }),
        // ...
    ]
};
```

```js
// src/Main.js
import * as THREE from 'three';
```

**Comment by pschroen** [comment]
In the latest version of the framework (`r17`) importing `three` as a module has now been removed to support worker threads via `importScripts()`.

Additionally the original ask of only importing parts of three.js currently isn't possible, even with tree-shaking. See mrdoob/three.js#10711 for reference.
